input_size: 512
center_crop_size: 1200
crop_size: 800
batch_size: 16
grad_accum: 3
warmup_epochs: 20
uptrain_epochs: 100
lr_init_warmup: 1e-5
lr_max_warmup: 1e-3
lr_init_uptrain: 1e-7
lr_max_uptrain: 5e-4
normalize: False
num_tta: 50
warmup_out: "warmup.model"
uptrain_out: "uptrain.model"
model_name: "seresnext50_32x4d"
head: "bestfitting"
concat_pool: False
loss: "SoftTargetCrossEntropy"
image_out: True
hard_examples_topk: 32
train_dir: './input/Train'
val_dir: None
test_dir: './input/Test'
val_size: 0.1
grayscale: False
pretrain: "ImageNet"
no_validation: False
flip: True
preproc: True
